import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import { ScoresProvider } from "../context/ScoresContext"; // Importa el proveedor del contexto

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ScoresProvider> {/* Envuelve el contenido con el proveedor */}
          <header><NavBar/></header>
          {children}
        </ScoresProvider>
      </body>
    </html>
  );
}

